SELECT * FROM 
Accounts

BEGIN TRANSACTION
DELETE FROM Accounts Where Id = 6

ALTER TABLE Accounts
ADD IsDeleted BIT 

ROLLBACK

GO

CREATE OR ALTER TRIGGER tr_AccountSoftDelete
ON Accounts
INSTEAD OF DELETE 
AS
UPDATE Accounts 
SET IsDeleted = 1
WHERE Id IN (SELECT Id FROM deleted)

GO

CREATE TABLE Logs
(
	LogId INT PRIMARY KEY IDENTITY (1, 1),
	AccountId INT FOREIGN KEY REFERENCES Accounts(Id),
	OldSum DECIMAL NOT NULL,
	NewSum DECIMAL NOT NULL
)

CREATE OR ALTER TRIGGER