CREATE DATABASE EuroLeagues
USE EuroLeagues

CREATE TABLE Leagues
(
	Id INT PRIMARY KEY IDENTITY (1, 1),
	[Name] NVARCHAR(50) NOT NULL
)

CREATE TABLE Teams
(
	Id INT PRIMARY KEY IDENTITY (1, 1),
	[Name] NVARCHAR(50) UNIQUE NOT NULL,
	City NVARCHAR(50) NOT NULL
	LeagueId INT FOREIGN KEY REFERENCES Leagues(Id) NOT NULL
)

CREATE TABLE Players
(
	Id INT PRIMARY KEY IDENTITY (1, 1),
	[Name] NVARCHAR(100) NOT NULL,
	Position NVARCHAR(20) NOT NULL
)

CREATE TABLE Matches
(
	Id INT PRIMARY KEY IDENTITY (1, 1),
	HomeTeamId INT FOREIGN KEY REFERENCES Teams(Id) NOT NULL,
	AwayTeamId INT FOREIGN KEY REFERENCES Teams(Id) NOT NULL,
	MatchDate DATETIME2 NOT NULL,
	HomeTeamGoals INT NOT NULL DEFAULT 0,
	AwayTeamGoals INT NOT NULL DEFAULT 0,
	LeagueId INT FOREIGN KEY REFERENCES Leagues(Id) NOT NULL
)

CREATE TABLE PlayersTeams
(
	PRIMARY KEY(PlayerId, TeamId),
	PlayerId INT FOREIGN KEY REFERENCES Players(Id),
	TeamId INT FOREIGN KEY REFERENCES Players(Id),
)

CREATE TABLE PlayerStats
(
	PRIMARY KEY(PlayerId),
	PlayerId INT FOREIGN KEY REFERENCES Players(Id),
	Goals INT NOT NULL DEFAULT 0,
	Assists INT NOT NULL DEFAULT 0
)

CREATE TABLE TeamStats
(
	PRIMARY KEY(TeamId),
	TeamId INT FOREIGN KEY REFERENCES Teams(Id),
	Wins INT NOT NULL DEFAULT 0,
	Draws INT NOT NULL DEFAULT 0,
	Losses INT NOT NULL DEFAULT 0,
)